import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import ReactQueryClientProvider from "@mm/modules/react/sections/components/ReactQueryClientProvider";
import Header from "@mm/modules/react/sections/components/Header";
import { checkUser } from "@mm/lib/checkUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await checkUser();

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ReactQueryClientProvider>
            <Header />
            <main>{children}</main>
          </ReactQueryClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
